server.port: 9091
kafka:
 bootstrap_address: 172.26.0.5:9092
 topic-name: testik
 group_id: testGroup

spring:
 application:
  name: "kotlin-project"
 cloud:
  bootstrap:
   enabled: true
  zookeeper:
   connect-string: 172.26.0.2:2181
   enabled: true
   config:
    root: '/dd/configs'
    enabled: true
    defaultContext: 'default'
    profileSeparator: '::'