server.port: 9091
kafka:
  bootstrap_address: localhost:9092
  topic-name: testik
  group_id: testGroup

elastic:
  host: localhost:9200

spring:
  application:
    name: "kotlin-project"
  cloud:
    bootstrap:
      enabled: true
    zookeeper:
      connect-string: localhost:2181
      enabled: true
      config:
        root: '/dd/configs'
        enabled: true
        defaultContext: 'default'
        profileSeparator: '::'