server.port: 9091
kafka:
  bootstrap_address: 172.21.0.6:9092
  topic-name: cars6
  group_id: testGroup2

elastic:
  host: 172.21.0.4:9200

spring:
  application:
    name: "kotlin-project"
  cloud:
    bootstrap:
      enabled: true
    zookeeper:
      connect-string: 172.21.0.5:2181
      enabled: true
      config:
        root: '/dd/configs'
        enabled: true
        defaultContext: 'default'
        profileSeparator: '::'