server.port: 9091
kafka:
  bootstrap_address: 10.5.0.40:9092
  topic-name: cars6
  group_id: testGroup2

elastic:
  host: 10.5.0.20:9200

spring:
  application:
    name: "kotlin-project"
  cloud:
    bootstrap:
      enabled: true
    zookeeper:
      connect-string: 10.5.0.45:2181
      enabled: true
      config:
        root: '/dd/configs'
        enabled: true
        defaultContext: 'default'
        profileSeparator: '::'