server.port: 9091
kafka:
  bootstrap_address: localhost:9093
  produce-topic-name: cars7
  consume-topic-name: fullfillment3.cars.car
  group_id: testGroup2

elastic:
  host: localhost:9200

spring:
  application:
    name: "kotlin-project"
  cloud:
    bootstrap:
      enabled: true
    zookeeper:
      connect-string: localhost:2181
      enabled: true
      config:
        root: '/dd/configs'
        enabled: true
        defaultContext: 'default'
        profileSeparator: '::'