PUT http://localhost:9200/cars8
Content-Type: application/json

{
  "settings": {
    "index.number_of_replicas": 0,
    "index.number_of_shards": 2,
    "index.refresh_interval": "30s",
    "index.codec": "best_compression",
    "index.sort.field": [
      "year",
      "car_id"
    ],
    "index.sort.order": [
      "desc",
      "asc"
    ]
  },
  "mappings": {
    "properties": {
      "properties": {
        "enabled": false
      },
      "car_id": {
        "type": "keyword"
      },
      "year": {
        "type": "date",
        "format": "yyyy-MM-dd"
      },
      "mark": {
        "type": "keyword"
      },
      "mileage": {
        "type": "integer"
      }
    }
  }
}

###
