PUT http://localhost:8083/connectors/simple-elasticsearch-connector/config
Content-Type: application/json

{
  "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "connection.url": "http://10.5.0.20:9200",
  "tasks.max": "1",
  "topics": "cars7",
  "name": "simple-elasticsearch-connector",
  "type.name": "_doc",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter.schemas.enable": "false",
  "schema.ignore": "true",
  "key.ignore": "true"
}

###
#Create connector
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "simple-elasticsearch-connector",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "connection.url": "http://10.5.0.20:9200",
    "tasks.max": "1",
    "topics": "cars7",
    "type.name": "_doc",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "schema.ignore": "true",
    "key.ignore": "true"
  }
}

###



GET http://localhost:8083/connectors


